### ISSUE TITLE
Export the dissambled code

### ISSUE THREAD

**Issue by Mte90** [AntonioND/giibiiadvance#13]
After a bit of hacking I saw that is possible to get the dissembled code with this emulator.
I am wondering if it is possible to add a new menu or a cli command to export it in a file to an easy inspections.

On my experimenting seems like that every line of the memory need to be disassembled but there is a loop that show only max 39 lines. 
There is a way to do a loop to parse the whole and generate it?

I have not s much experience C and is not clear for me to find where is stored the memory.

**Comment by AntonioND** [comment]
Are you talking about GB code or GBA code? Because in either case there are other disassemblers you could use.

**Comment by Mte90** [comment]
GBA for now, I tried different disassemblers but often they are incomplete or don't include the assembly code but just the bytes.
I am trying now patching the `bin2c` to use the emulator core to export that.

**Comment by Mte90** [comment]
I got something at https://gist.github.com/Mte90/029987956cc7c186a83dff404472443b but is a c&p with some function commented because require a lot of things and I don't know how to replicate their behaviour.
Right now works, generate a file with a lot of missing ram and unknown code.

**Comment by AntonioND** [comment]
Use ``objdump``, Ghidra, IDA...

**Comment by Mte90** [comment]
I tied with them, `arm-none-eabi-objdump` is the most simple by cli but is not so 100% perfect.
The others are very slow, my idea was to get the assembly code so I can execute on that scripts to search and other things. As the debugger of this emulator has everything I was thinking that was possible to get that code with real memory addresses.

**Comment by AntonioND** [comment]
Do you mean that the base address of the code isn't right? I think there is an option for that (vma or something).

What about no$gba? https://problemkaputt.de/gba.htm I think you can export all the disassembly.

**Comment by Mte90** [comment]
nogba it isn't for linux, the export in my c&p is not right I guess because I commented some functions that i cannot replicate without the full emulator.

**Comment by AntonioND** [comment]
no$gba runs pretty well under wine.

In any case, I'm not interested in doing this, that's why I keep offering you solutions. Disassembling things isn't easy (What is code? What is data? What is ARM? What is Thumb?). In practice, my disassembly code only works if you have some reference. If I'm in address X, it's fair to assume that everything around it is code, and that the mode is the same. Doing it to a full file is not correct, though. I think that no$gba is clever enough to follow jumps and to do that kind of things during the disassembly, so the result is accurate.

**Comment by Mte90** [comment]
Thanks for the clarification, after a bit of investigating I saw some problems in fact on working on that because the memory address are not right (after all is not running inside the emulator) etc

**Comment by AntonioND** [comment]
Yes, that's what I would expect. Getting a correct disassembly is hard. The disassembler of emulators usually rely on the fact that it's a dynamic disassembly so some of the problems are mitigated (like disassembling data as code, in the emulator you just don't run that).
