### ISSUE TITLE
Makefile:14: recipe for target 'gb_core/camera.o' failed

### ISSUE THREAD

**Issue by AlpacaMan233** [AntonioND/giibiiadvance#9]
I compile the sources on ubuntu 16.04, get error "Makefile:14: recipe for target 'gb_core/camera.o' failed". I have opencv3 installed. How to resolve?

**Comment by AntonioND** [comment]
I haven't worked on this in a long time. It's possible that I'll try to find some time and at least create a new release (a lot of things changed between the last one and the current code) but I can't promise anything...

If you find a fix and want to contribute with pull request, I'd be happy to accept it.

**Comment by AntonioND** [comment]
This can be tracked here: https://github.com/AntonioND/giibiiadvance/issues/11

Apparently the API of OpenCV has changed a lot since I wrote this code...

**Comment by AntonioND** [comment]
Fixed in https://github.com/AntonioND/giibiiadvance/commit/dab442953243c9c272c96042caa8b85a2824bbb3
